[id]
name = example_app
version = 8.0.0

[ui]
is_visible = false
show_in_nav = false
label = Example App

[launcher]
author = 
description = 
version = 8.0.0

[install]
is_configured = 0
build = 1

[package]
check_for_updates = false
id = example_app